/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package twitter;

import java.util.Scanner;



public class App {

  public static void main(String args[]) throws Exception{

	Scanner in = new Scanner(System.in);
	String s = "";
	
	Authenticator authenticator = new Authenticator();
	
	// ログイン済みならログイン情報をセットする
	authenticator.init();

	// ツイート、タイムラインの取得でTwitterServiceに実装
	TwitterService ts = new TwitterService();
	
	do{

		System.out.print("twitter commands >");

		s = in.nextLine();

		switch (s){
			// 終了
			case "quit":
				break;
			// ログイン
			case "login":
				login(authenticator);
				break;
			
			// タイムライン
			case "tl":
				ts.showTimeLine();
				break;
			// ツイート
			case "tw":
				ts.tweet();
				break;
			// ヘルプ
			case "help":
				help();
				break;
			default: 
				System.out.println(s + " command is not found.");
		}
	
	}while(!s.equals("quit"));

	System.out.println("See you!!");
	in.close();
	}

  public static void login(Authenticator authenticator){
	System.out.println("login command");
	authenticator.authenticate();
  }

  public static void help(){
	  System.out.println("tw: ツイートする");
	  System.out.println("tl: タイムライン見る");
	  System.out.println("quit: 終了");
  }
}
